name: Update README

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install @octokit/rest

      - name: Update Latest Repos Section
        run: node .github/scripts/updateRepos.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config user.name "choy-bot"
          git config user.email "choy@example.com"
          git add README.md
          git commit -m "📦 update latest repos"
          git push
